services:
  - type: web
    name: vikor-method
    env: docker
    plan: free
    branch: main
    # ⛔️ Jangan pakai buildCommand/startCommand karena Dockerfile sudah mengatur semua
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:Zdehf/hGFZ8HjK0ZpcjulDewCUklS4m0wQUTL9d3ZPo=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://vikor-method.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
