services:
  - type: web
    name: vikor-method
    env: docker
    plan: free
    branch: main
    buildCommand: ""        # Build ditangani sepenuhnya di Dockerfile
    startCommand: ""        # Apache auto-start (CMD di Dockerfile)
    envVars:
      # ✅ Laravel Environment
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:jMPGWVH3n9kMt45SWLcEx3zAIdIeviBM0TwryxnkImU=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://vikor-method-2lgv.onrender.com
      - key: APP_TIMEZONE
        value: Asia/Jakarta

      # ✅ PostgreSQL (Neon.tech)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-proud-water-afz2m2wb-pooler.c-2.us-west-2.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_CPTrxwl78HsQ
      - key: DB_SSLMODE
        value: require

      # ✅ Log, Cache, Session, Queue (lokal file-based)
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

      # ✅ Email (log mode - nonaktifkan pengiriman email real)
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: robbyadiyasaputra@gmail.com
      - key: MAIL_FROM_NAME
        value: "VikorMethod"

      # ✅ Vite (untuk asset path - tidak wajib tapi aman)
      - key: VITE_APP_URL
        value: https://vikor-method-2lgv.onrender.com
